### PR TITLE
fix(nx-serverless): nx deploy throw warning when checking dependencies

### LINKED ISSUE #36: [BUG] Could not check for peer dependencies of x package
I am getting below warning when deploying our service

```
getting external modules
create a package.json with first level dependencies
Serverless: WARNING: Could not check for peer dependencies of serverless-mysql
generate lock entry for yarn for dependency graph to work.
get the packagelist with dependency graph and depth=2 level
re-writing package.json with dependency-graphs
Serverless: WARNING: Could not determine version of module tslib
Serverless: WARNING: Could not check for peer dependencies of serverless-mysql
run packager to  install node_modules
```

Here is the sample code of my Lambda function

```
// Require and initialize outside of your main handler
import * as serverlessMysql from 'serverless-mysql';
const mysql = serverlessMysql({
  config: {
    host     : process.env.ENDPOINT,
    database : process.env.DATABASE,
    user     : process.env.USERNAME,
    password : process.env.PASSWORD
  }
})

// Main handler function
export const handler = async (event, context) => {
  // Run your query
  let results = await mysql.query('SELECT * FROM table')

  // Run clean up function
  await mysql.end()

  // Return the results
  return results
}
```

I have debugged and figured out that the modulePackagePath is invalid (the root dir is duplicated in the path), see below example

modulePackagePath /Users/hoangle/Documents/Working/Source/my-sls-api/Users/hoangle/Documents/Working/Source/my-sls-api/node_modules/serverless-mysql/package.json

### PR DESCRIPTION
**Pull request by hoang-innomizetech**
* Fix wrong module path calculator when checking peer dependencies for external module
* Add missing packageJson parameter when calling getProdModules function

Fixes #36

### CODE REVIEW

**Comment by wickstargazer** [comment]
should we write a test for this? or have a small testing session? I am afraid it will affect older versions. Unless you have tested it out 😄

**Comment by hoang-innomizetech** [comment]
Sorry, currently there is no test related to packing and I don't have too much time to write tests. But I have tested again our workspace and it is working as expected.

**Comment by wickstargazer** [comment]
ok, let me test on ours, which is using the old version if it works i will push it through today 😄 
I will look into how difficult to write the test for packager as well.
Another question, do you think its a good idea to move out the packager as another plugin?

**Comment by hoang-innomizetech** [comment]
@wickstargazer  I am still evaluating your plugin for packaging, it has some cons and pros. The package size when using your plugin is a bit higher than the old version when we use serverless-webpack plugin.

I can see that right now we don't have any way to exclude a package from workspace.json or serverless.yml file. I have tested and it seems we have some bugs here.

**Comment by wickstargazer** [comment]
Thats a work in progress and the reason it should be higher is because of the nature of the repo...need to enhance it to fit the use cases 😀

**Comment by hoang-innomizetech** [comment]
Yeah, I would love to see your ideas as well as we can discuss it further. Our team here using Serverless a lot of we have changed to use Nx for a year. We are using your plugin to set up a new workspace with many sls services. Packaging and create as shared AWS Lambda Layer are my to-do list.

**Pull request merged**
